### ISSUE TITLE
NFS is not responding with npm

### ISSUE THREAD

**Issue by kadet1090** [winnfsd/vagrant-winnfsd#61]
There seems to be some problem with larger operations. When I for example try to remove directory which contains many dirs and files (about 533 dirs, dependencies downloaded by npm, don't ask..) nfs is not responding and system throws I/O error. In fact I can't even install packages via npm because of that because i'm still getting such an error:

```
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.39
npm ERR! npm  v3.0.0
npm ERR! path /var/www/lionheart/node_modules/.staging
npm ERR! code EIO
npm ERR! errno 55

npm ERR! EIO, rmdir '/var/www/lionheart/node_modules/.staging'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

And with that comes few messages in `dmesg`:

```
[ 1429.984995] nfs: server 172.28.128.1 not responding, still trying
[ 1429.986011] nfs: server 172.28.128.1 OK
[ 1429.989065] NFS: server 172.28.128.1 error: fileid changed
[ 1429.989065] fsid 0:26: expected fileid 0x38db, got 0x2086
```

I'm using windows 8.1 Pro as host, and puppetlabs/ubuntu-14.04-64-puppet as my vm in virtualbox.

**Comment by kadet1090** [comment]
After taking a quick look at winnfsd logs it looks like it might be problem with npm itself, which is not deleting all directory content befere trying to rmdir (and it basicaly sucks, because it spams console with "WRITE" messages on every log line). But I also noticed such Input/Output errors when just deleting large amount of files by myself. Oh, and I updated winnfsd.exe to version mentioned in #60, and for now everything looks fine, but i will try to give more feedback if needed.

**Comment by worthwhileindustries** [comment]
Win 8.1, VBOX 5, Vagrant 1.7.4, 

I get errors installing packages as well.. It works fine if I use "npm some package -g" to install the package globally. Here's the output on NFS

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/bin/npm', 'install', 'express' ]
2 info using npm@1.3.6
3 info using node@v0.10.36
4 verbose node symlink /bin/node
5 verbose cache add [ 'express', null ]
6 verbose cache add name=undefined spec="express" args=["express",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'express',
7 verbose parsed url   path: 'express',
7 verbose parsed url   href: 'express' }
8 silly lockFile f3c62de4-express express
9 verbose lock express /root/.npm/f3c62de4-express.lock
10 silly lockFile f3c62de4-express express
11 silly lockFile f3c62de4-express express
12 verbose addNamed [ 'express', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 64a534c1-express express@
15 verbose lock express@ /root/.npm/64a534c1-express.lock
16 silly addNameRange { name: 'express', range: '*', hasData: false }
17 verbose url raw express
18 verbose url resolving [ 'https://registry.npmjs.org/', './express' ]
19 verbose url resolved https://registry.npmjs.org/express
20 info trying registry request attempt 1 at 23:33:35
21 http GET https://registry.npmjs.org/express
22 http 200 https://registry.npmjs.org/express
23 silly registry.get cb [ 200,
23 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly registry.get     etag: '"1IJUA98FB6TOBXDV280VZQUID"',
23 silly registry.get     'content-type': 'application/json',
23 silly registry.get     'cache-control': 'max-age=60',
23 silly registry.get     'content-length': '526076',
23 silly registry.get     'accept-ranges': 'bytes',
23 silly registry.get     date: 'Thu, 20 Aug 2015 05:33:35 GMT',
23 silly registry.get     via: '1.1 varnish',
23 silly registry.get     age: '33',
23 silly registry.get     connection: 'keep-alive',
23 silly registry.get     'x-served-by': 'cache-sjc3130-SJC',
23 silly registry.get     'x-cache': 'HIT',
23 silly registry.get     'x-cache-hits': '1',
23 silly registry.get     'x-timer': 'S1440048815.494274,VS0,VE3',
23 silly registry.get     vary: 'Accept' } ]
24 silly addNameRange number 2 { name: 'express', range: '*', hasData: true }
25 silly addNameRange versions [ 'express',
25 silly addNameRange   [ '0.14.0',
25 silly addNameRange     '0.14.1',
25 silly addNameRange     '1.0.0',
25 silly addNameRange     '1.0.1',
25 silly addNameRange     '1.0.2',
25 silly addNameRange     '1.0.3',
25 silly addNameRange     '1.0.4',
25 silly addNameRange     '1.0.5',
25 silly addNameRange     '1.0.6',
25 silly addNameRange     '1.0.7',
25 silly addNameRange     '1.0.8',
25 silly addNameRange     '2.0.0',
25 silly addNameRange     '2.1.0',
25 silly addNameRange     '2.1.1',
25 silly addNameRange     '2.2.0',
25 silly addNameRange     '2.2.1',
25 silly addNameRange     '2.2.2',
25 silly addNameRange     '2.3.0',
25 silly addNameRange     '2.3.1',
25 silly addNameRange     '2.3.2',
25 silly addNameRange     '2.3.3',
25 silly addNameRange     '2.3.4',
25 silly addNameRange     '2.3.5',
25 silly addNameRange     '2.3.6',
25 silly addNameRange     '2.3.7',
25 silly addNameRange     '2.3.8',
25 silly addNameRange     '2.3.9',
25 silly addNameRange     '2.3.10',
25 silly addNameRange     '2.3.11',
25 silly addNameRange     '2.3.12',
25 silly addNameRange     '2.4.0',
25 silly addNameRange     '2.4.1',
25 silly addNameRange     '2.4.2',
25 silly addNameRange     '2.4.3',
25 silly addNameRange     '2.4.4',
25 silly addNameRange     '2.4.5',
25 silly addNameRange     '2.4.6',
25 silly addNameRange     '2.4.7',
25 silly addNameRange     '2.5.0',
25 silly addNameRange     '2.5.1',
25 silly addNameRange     '2.5.2',
25 silly addNameRange     '2.5.3',
25 silly addNameRange     '2.5.4',
25 silly addNameRange     '2.5.5',
25 silly addNameRange     '2.5.6',
25 silly addNameRange     '2.5.7',
25 silly addNameRange     '2.5.8',
25 silly addNameRange     '2.5.9',
25 silly addNameRange     '2.5.10',
25 silly addNameRange     '2.5.11',
25 silly addNameRange     '3.0.0',
25 silly addNameRange     '3.0.1',
25 silly addNameRange     '3.0.2',
25 silly addNameRange     '3.0.3',
25 silly addNameRange     '3.0.4',
25 silly addNameRange     '3.0.5',
25 silly addNameRange     '3.0.6',
25 silly addNameRange     '3.1.0',
25 silly addNameRange     '3.1.1',
25 silly addNameRange     '3.1.2',
25 silly addNameRange     '3.2.0',
25 silly addNameRange     '3.2.1',
25 silly addNameRange     '3.2.2',
25 silly addNameRange     '3.2.3',
25 silly addNameRange     '3.2.4',
25 silly addNameRange     '3.2.5',
25 silly addNameRange     '3.2.6',
25 silly addNameRange     '3.3.0',
25 silly addNameRange     '3.3.1',
25 silly addNameRange     '3.3.2',
25 silly addNameRange     '3.3.3',
25 silly addNameRange     '3.3.4',
25 silly addNameRange     '3.3.5',
25 silly addNameRange     '3.3.6',
25 silly addNameRange     '1.0.0-beta',
25 silly addNameRange     '1.0.0-beta2',
25 silly addNameRange     '1.0.0-rc',
25 silly addNameRange     '1.0.0-rc2',
25 silly addNameRange     '1.0.0-rc3',
25 silly addNameRange     '1.0.0-rc4',
25 silly addNameRange     '2.0.0-beta',
25 silly addNameRange     '2.0.0-beta2',
25 silly addNameRange     '2.0.0-beta3',
25 silly addNameRange     '2.0.0-rc',
25 silly addNameRange     '2.0.0-rc2',
25 silly addNameRange     '2.0.0-rc3',
25 silly addNameRange     '3.0.0-alpha1',
25 silly addNameRange     '3.0.0-alpha2',
25 silly addNameRange     '3.0.0-alpha3',
25 silly addNameRange     '3.0.0-alpha4',
25 silly addNameRange     '3.0.0-alpha5',
25 silly addNameRange     '3.0.0-beta1',
25 silly addNameRange     '3.0.0-beta2',
25 silly addNameRange     '3.0.0-beta3',
25 silly addNameRange     '3.0.0-beta4',
25 silly addNameRange     '3.0.0-beta6',
25 silly addNameRange     '3.0.0-beta7',
25 silly addNameRange     '3.0.0-rc1',
25 silly addNameRange     '3.0.0-rc2',
25 silly addNameRange     '3.0.0-rc3',
25 silly addNameRange     '3.0.0-rc4',
25 silly addNameRange     '3.0.0-rc5',
25 silly addNameRange     '3.3.7',
25 silly addNameRange     '3.3.8',
25 silly addNameRange     '3.4.0',
25 silly addNameRange     '3.4.1',
25 silly addNameRange     '3.4.2',
25 silly addNameRange     '3.4.3',
25 silly addNameRange     '3.4.4',
25 silly addNameRange     '3.4.5',
25 silly addNameRange     '3.4.6',
25 silly addNameRange     '3.4.7',
25 silly addNameRange     '3.4.8',
25 silly addNameRange     '4.0.0-rc1',
25 silly addNameRange     '4.0.0-rc2',
25 silly addNameRange     '3.5.0',
25 silly addNameRange     '4.0.0-rc3',
25 silly addNameRange     '4.0.0-rc4',
25 silly addNameRange     '3.5.1',
25 silly addNameRange     '4.0.0',
25 silly addNameRange     '3.5.2',
25 silly addNameRange     '4.1.0',
25 silly addNameRange     '4.1.1',
25 silly addNameRange     '3.5.3',
25 silly addNameRange     '4.1.2',
25 silly addNameRange     '3.6.0',
25 silly addNameRange     '4.2.0',
25 silly addNameRange     '3.7.0',
25 silly addNameRange     '3.8.0',
25 silly addNameRange     '4.3.0',
25 silly addNameRange     '4.3.1',
25 silly addNameRange     '3.8.1',
25 silly addNameRange     '4.3.2',
25 silly addNameRange     '3.9.0',
25 silly addNameRange     '4.4.0',
25 silly addNameRange     '4.4.1',
25 silly addNameRange     '3.10.0',
25 silly addNameRange     '3.10.1',
25 silly addNameRange     '3.10.2',
25 silly addNameRange     '3.10.3',
25 silly addNameRange     '3.10.4',
25 silly addNameRange     '4.4.2',
25 silly addNameRange     '3.10.5',
25 silly addNameRange     '4.4.3',
25 silly addNameRange     '3.11.0',
25 silly addNameRange     '4.4.4',
25 silly addNameRange     '3.12.0',
25 silly addNameRange     '3.12.1',
25 silly addNameRange     '4.4.5',
25 silly addNameRange     '3.13.0',
25 silly addNameRange     '4.5.0',
25 silly addNameRange     '4.5.1',
25 silly addNameRange     '3.14.0',
25 silly addNameRange     '4.6.0',
25 silly addNameRange     '4.6.1',
25 silly addNameRange     '3.15.0',
25 silly addNameRange     '4.7.0',
25 silly addNameRange     '3.15.1',
25 silly addNameRange     '4.7.1',
25 silly addNameRange     '3.15.2',
25 silly addNameRange     '4.7.2',
25 silly addNameRange     '4.7.3',
25 silly addNameRange     '3.15.3',
25 silly addNameRange     '4.7.4',
25 silly addNameRange     '3.16.0',
25 silly addNameRange     '4.8.0',
25 silly addNameRange     '3.16.1',
25 silly addNameRange     '4.8.1',
25 silly addNameRange     '3.16.2',
25 silly addNameRange     '4.8.2',
25 silly addNameRange     '3.16.3',
25 silly addNameRange     '3.16.4',
25 silly addNameRange     '4.8.3',
25 silly addNameRange     '3.16.5',
25 silly addNameRange     '3.16.6',
25 silly addNameRange     '4.8.4',
25 silly addNameRange     '3.16.7',
25 silly addNameRange     '4.8.5',
25 silly addNameRange     '3.16.8',
25 silly addNameRange     '4.8.6',
25 silly addNameRange     '3.16.9',
25 silly addNameRange     '4.8.7',
25 silly addNameRange     '3.16.10',
25 silly addNameRange     '4.8.8',
25 silly addNameRange     '3.17.0',
25 silly addNameRange     '3.17.1',
25 silly addNameRange     '4.9.0',
25 silly addNameRange     '3.17.2',
25 silly addNameRange     '4.9.1',
25 silly addNameRange     '4.9.2',
25 silly addNameRange     '3.17.3',
25 silly addNameRange     '4.9.3',
25 silly addNameRange     '3.17.4',
25 silly addNameRange     '4.9.4',
25 silly addNameRange     '3.17.5',
25 silly addNameRange     '4.9.5',
25 silly addNameRange     '3.17.6',
25 silly addNameRange     '3.17.7',
25 silly addNameRange     '4.9.6',
25 silly addNameRange     '4.9.7',
25 silly addNameRange     '3.17.8',
25 silly addNameRange     '4.9.8',
25 silly addNameRange     '3.18.0',
25 silly addNameRange     '3.18.1',
25 silly addNameRange     '4.10.0',
25 silly addNameRange     '3.18.2',
25 silly addNameRange     '4.10.1',
25 silly addNameRange     '5.0.0-alpha.1',
25 silly addNameRange     '3.18.3',
25 silly addNameRange     '4.10.2',
25 silly addNameRange     '3.18.4',
25 silly addNameRange     '4.10.3',
25 silly addNameRange     '4.10.4',
25 silly addNameRange     '4.10.5',
25 silly addNameRange     '3.18.5',
25 silly addNameRange     '3.18.6',
25 silly addNameRange     '4.10.6',
25 silly addNameRange     '4.10.7',
25 silly addNameRange     '3.19.0',
25 silly addNameRange     '4.10.8',
25 silly addNameRange     '4.11.0',
25 silly addNameRange     '3.19.1',
25 silly addNameRange     '4.11.1',
25 silly addNameRange     '3.19.2',
25 silly addNameRange     '4.11.2',
25 silly addNameRange     '3.20.0',
25 silly addNameRange     '4.12.0',
25 silly addNameRange     '3.20.1',
25 silly addNameRange     '4.12.1',
25 silly addNameRange     '4.12.2',
25 silly addNameRange     '3.20.2',
25 silly addNameRange     '4.12.3',
25 silly addNameRange     '3.20.3',
25 silly addNameRange     '4.12.4',
25 silly addNameRange     '3.21.0',
25 silly addNameRange     '4.13.0',
25 silly addNameRange     '3.21.1',
25 silly addNameRange     '4.13.1',
25 silly addNameRange     '5.0.0-alpha.2',
25 silly addNameRange     '3.21.2',
25 silly addNameRange     '4.13.2',
25 silly addNameRange     '4.13.3' ] ]
26 verbose addNamed [ 'express', '4.13.3' ]
27 verbose addNamed [ '4.13.3', '4.13.3' ]
28 silly lockFile 51f1744e-express-4-13-3 express@4.13.3
29 verbose lock express@4.13.3 /root/.npm/51f1744e-express-4-13-3.lock
30 silly lockFile 0cf3ba70-s-org-express-express-4-13-3-tgz https://registry.npmjs.org/express/-/express-4.13.3.tgz
31 verbose lock https://registry.npmjs.org/express/-/express-4.13.3.tgz /root/.npm/0cf3ba70-s-org-express-express-4-13-3-tgz.lock
32 verbose addRemoteTarball [ 'https://registry.npmjs.org/express/-/express-4.13.3.tgz',
32 verbose addRemoteTarball   'ddb2f1fb4502bf33598d2b032b037960ca6c80a3' ]
33 info retry fetch attempt 1 at 23:33:36
34 verbose fetch to= /root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/tmp.tgz
35 http GET https://registry.npmjs.org/express/-/express-4.13.3.tgz
36 http 200 https://registry.npmjs.org/express/-/express-4.13.3.tgz
37 verbose tar unpack /root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/tmp.tgz
38 silly lockFile b8e969dc-16037-0-9324867615941912-package tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
39 verbose lock tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package /root/.npm/b8e969dc-16037-0-9324867615941912-package.lock
40 silly lockFile 0458aeed-16037-0-9324867615941912-tmp-tgz tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/tmp.tgz
41 verbose lock tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/tmp.tgz /root/.npm/0458aeed-16037-0-9324867615941912-tmp-tgz.lock
42 silly gunzTarPerm modes [ '755', '644' ]
43 silly gunzTarPerm extractEntry package.json
44 silly gunzTarPerm modified mode [ 'package.json', 438, 420 ]
45 silly gunzTarPerm extractEntry LICENSE
46 silly gunzTarPerm modified mode [ 'LICENSE', 438, 420 ]
47 silly gunzTarPerm extractEntry index.js
48 silly gunzTarPerm modified mode [ 'index.js', 438, 420 ]
49 silly gunzTarPerm extractEntry History.md
50 silly gunzTarPerm modified mode [ 'History.md', 438, 420 ]
51 silly gunzTarPerm extractEntry Readme.md
52 silly gunzTarPerm modified mode [ 'Readme.md', 438, 420 ]
53 silly gunzTarPerm extractEntry lib/application.js
54 silly gunzTarPerm modified mode [ 'lib/application.js', 438, 420 ]
55 silly gunzTarPerm extractEntry lib/express.js
56 silly gunzTarPerm modified mode [ 'lib/express.js', 438, 420 ]
57 silly gunzTarPerm extractEntry lib/request.js
58 silly gunzTarPerm modified mode [ 'lib/request.js', 438, 420 ]
59 silly gunzTarPerm extractEntry lib/response.js
60 silly gunzTarPerm modified mode [ 'lib/response.js', 438, 420 ]
61 silly gunzTarPerm extractEntry lib/utils.js
62 silly gunzTarPerm modified mode [ 'lib/utils.js', 438, 420 ]
63 silly gunzTarPerm extractEntry lib/view.js
64 silly gunzTarPerm modified mode [ 'lib/view.js', 438, 420 ]
65 silly gunzTarPerm extractEntry lib/middleware/init.js
66 silly gunzTarPerm modified mode [ 'lib/middleware/init.js', 438, 420 ]
67 silly gunzTarPerm extractEntry lib/middleware/query.js
68 silly gunzTarPerm modified mode [ 'lib/middleware/query.js', 438, 420 ]
69 silly gunzTarPerm extractEntry lib/router/index.js
70 silly gunzTarPerm modified mode [ 'lib/router/index.js', 438, 420 ]
71 silly gunzTarPerm extractEntry lib/router/layer.js
72 silly gunzTarPerm modified mode [ 'lib/router/layer.js', 438, 420 ]
73 silly gunzTarPerm extractEntry lib/router/route.js
74 silly gunzTarPerm modified mode [ 'lib/router/route.js', 438, 420 ]
75 silly lockFile b8e969dc-16037-0-9324867615941912-package tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
76 silly lockFile b8e969dc-16037-0-9324867615941912-package tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
77 silly lockFile 0458aeed-16037-0-9324867615941912-tmp-tgz tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/tmp.tgz
78 silly lockFile 0458aeed-16037-0-9324867615941912-tmp-tgz tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/tmp.tgz
79 verbose tar pack [ '/root/.npm/express/4.13.3/package.tgz',
79 verbose tar pack   '/root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package' ]
80 verbose tarball /root/.npm/express/4.13.3/package.tgz
81 verbose folder /root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
82 silly lockFile b8e969dc-16037-0-9324867615941912-package tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
83 verbose lock tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package /root/.npm/b8e969dc-16037-0-9324867615941912-package.lock
84 silly lockFile 8bafe4d1-t-npm-express-4-13-3-package-tgz tar:///root/.npm/express/4.13.3/package.tgz
85 verbose lock tar:///root/.npm/express/4.13.3/package.tgz /root/.npm/8bafe4d1-t-npm-express-4-13-3-package-tgz.lock
86 silly lockFile b8e969dc-16037-0-9324867615941912-package tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
87 silly lockFile b8e969dc-16037-0-9324867615941912-package tar:///root/tmp/npm-25605-eGc8Rhyz/1440048816037-0.9324867615941912/package
88 silly lockFile 8bafe4d1-t-npm-express-4-13-3-package-tgz tar:///root/.npm/express/4.13.3/package.tgz
89 silly lockFile 8bafe4d1-t-npm-express-4-13-3-package-tgz tar:///root/.npm/express/4.13.3/package.tgz
90 silly lockFile 74fe5087-root-npm-express-4-13-3-package /root/.npm/express/4.13.3/package
91 verbose lock /root/.npm/express/4.13.3/package /root/.npm/74fe5087-root-npm-express-4-13-3-package.lock
92 silly lockFile 74fe5087-root-npm-express-4-13-3-package /root/.npm/express/4.13.3/package
93 silly lockFile 74fe5087-root-npm-express-4-13-3-package /root/.npm/express/4.13.3/package
94 verbose tar unpack /root/.npm/express/4.13.3/package.tgz
95 silly lockFile bdbe1c0d--root-npm-express-4-13-3-package tar:///root/.npm/express/4.13.3/package
96 verbose lock tar:///root/.npm/express/4.13.3/package /root/.npm/bdbe1c0d--root-npm-express-4-13-3-package.lock
97 silly lockFile 8bafe4d1-t-npm-express-4-13-3-package-tgz tar:///root/.npm/express/4.13.3/package.tgz
98 verbose lock tar:///root/.npm/express/4.13.3/package.tgz /root/.npm/8bafe4d1-t-npm-express-4-13-3-package-tgz.lock
99 silly gunzTarPerm modes [ '755', '644' ]
100 silly gunzTarPerm extractEntry package.json
101 silly gunzTarPerm extractEntry LICENSE
102 silly gunzTarPerm extractEntry index.js
103 silly gunzTarPerm extractEntry History.md
104 silly gunzTarPerm extractEntry Readme.md
105 silly gunzTarPerm extractEntry lib/application.js
106 silly gunzTarPerm extractEntry lib/express.js
107 silly gunzTarPerm extractEntry lib/request.js
108 silly gunzTarPerm extractEntry lib/response.js
109 silly gunzTarPerm extractEntry lib/utils.js
110 silly gunzTarPerm extractEntry lib/view.js
111 silly gunzTarPerm extractEntry lib/middleware/init.js
112 silly gunzTarPerm extractEntry lib/middleware/query.js
113 silly gunzTarPerm extractEntry lib/router/index.js
114 silly gunzTarPerm extractEntry lib/router/layer.js
115 silly gunzTarPerm extractEntry lib/router/route.js
116 silly lockFile bdbe1c0d--root-npm-express-4-13-3-package tar:///root/.npm/express/4.13.3/package
117 silly lockFile bdbe1c0d--root-npm-express-4-13-3-package tar:///root/.npm/express/4.13.3/package
118 silly lockFile 8bafe4d1-t-npm-express-4-13-3-package-tgz tar:///root/.npm/express/4.13.3/package.tgz
119 silly lockFile 8bafe4d1-t-npm-express-4-13-3-package-tgz tar:///root/.npm/express/4.13.3/package.tgz
120 verbose chmod /root/.npm/express/4.13.3/package.tgz 644
121 verbose chown /root/.npm/express/4.13.3/package.tgz [ 0, 0 ]
122 silly lockFile 0cf3ba70-s-org-express-express-4-13-3-tgz https://registry.npmjs.org/express/-/express-4.13.3.tgz
123 silly lockFile 0cf3ba70-s-org-express-express-4-13-3-tgz https://registry.npmjs.org/express/-/express-4.13.3.tgz
124 silly lockFile 51f1744e-express-4-13-3 express@4.13.3
125 silly lockFile 51f1744e-express-4-13-3 express@4.13.3
126 silly lockFile 64a534c1-express express@
127 silly lockFile 64a534c1-express express@
128 silly resolved [ { name: 'express',
128 silly resolved     description: 'Fast, unopinionated, minimalist web framework',
128 silly resolved     version: '4.13.3',
128 silly resolved     author: { name: 'TJ Holowaychuk', email: 'tj@vision-media.ca' },
128 silly resolved     contributors:
128 silly resolved      [ [Object],
128 silly resolved        [Object],
128 silly resolved        [Object],
128 silly resolved        [Object],
128 silly resolved        [Object],
128 silly resolved        [Object],
128 silly resolved        [Object] ],
128 silly resolved     license: 'MIT',
128 silly resolved     repository: { type: 'git', url: 'strongloop/express' },
128 silly resolved     homepage: 'http://expressjs.com/',
128 silly resolved     keywords:
128 silly resolved      [ 'express',
128 silly resolved        'framework',
128 silly resolved        'sinatra',
128 silly resolved        'web',
128 silly resolved        'rest',
128 silly resolved        'restful',
128 silly resolved        'router',
128 silly resolved        'app',
128 silly resolved        'api' ],
128 silly resolved     dependencies:
128 silly resolved      { accepts: '~1.2.12',
128 silly resolved        'array-flatten': '1.1.1',
128 silly resolved        'content-disposition': '0.5.0',
128 silly resolved        'content-type': '~1.0.1',
128 silly resolved        cookie: '0.1.3',
128 silly resolved        'cookie-signature': '1.0.6',
128 silly resolved        debug: '~2.2.0',
128 silly resolved        depd: '~1.0.1',
128 silly resolved        'escape-html': '1.0.2',
128 silly resolved        etag: '~1.7.0',
128 silly resolved        finalhandler: '0.4.0',
128 silly resolved        fresh: '0.3.0',
128 silly resolved        'merge-descriptors': '1.0.0',
128 silly resolved        methods: '~1.1.1',
128 silly resolved        'on-finished': '~2.3.0',
128 silly resolved        parseurl: '~1.3.0',
128 silly resolved        'path-to-regexp': '0.1.7',
128 silly resolved        'proxy-addr': '~1.0.8',
128 silly resolved        qs: '4.0.0',
128 silly resolved        'range-parser': '~1.0.2',
128 silly resolved        send: '0.13.0',
128 silly resolved        'serve-static': '~1.10.0',
128 silly resolved        'type-is': '~1.6.6',
128 silly resolved        'utils-merge': '1.0.0',
128 silly resolved        vary: '~1.0.1' },
128 silly resolved     devDependencies:
128 silly resolved      { after: '0.8.1',
128 silly resolved        ejs: '2.3.3',
128 silly resolved        istanbul: '0.3.17',
128 silly resolved        marked: '0.3.5',
128 silly resolved        mocha: '2.2.5',
128 silly resolved        should: '7.0.2',
128 silly resolved        supertest: '1.0.1',
128 silly resolved        'body-parser': '~1.13.3',
128 silly resolved        'connect-redis': '~2.4.1',
128 silly resolved        'cookie-parser': '~1.3.5',
128 silly resolved        'cookie-session': '~1.2.0',
128 silly resolved        'express-session': '~1.11.3',
128 silly resolved        jade: '~1.11.0',
128 silly resolved        'method-override': '~2.3.5',
128 silly resolved        morgan: '~1.6.1',
128 silly resolved        multiparty: '~4.1.2',
128 silly resolved        vhost: '~3.0.1' },
128 silly resolved     engines: { node: '>= 0.10.0' },
128 silly resolved     files: [ 'LICENSE', 'History.md', 'Readme.md', 'index.js', 'lib/' ],
128 silly resolved     scripts:
128 silly resolved      { test: 'mocha --require test/support/env --reporter spec --bail --check-leaks test/ test/acceptance/',
128 silly resolved        'test-ci': 'istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --require test/support/env --reporter spec --check-leaks test/ test/acceptance/',
128 silly resolved        'test-cov': 'istanbul cover node_modules/mocha/bin/_mocha -- --require test/support/env --reporter dot --check-leaks test/ test/acceptance/',
128 silly resolved        'test-tap': 'mocha --require test/support/env --reporter tap --check-leaks test/ test/acceptance/' },
128 silly resolved     readme: '[![Express Logo](https://i.cloudup.com/zfY6lL7eFa-3000x3000.png)](http://expressjs.com/)\n\n  Fast, unopinionated, minimalist web framework for [node](http://nodejs.org).\n\n  [![NPM Version][npm-image]][npm-url]\n  [![NPM Downloads][downloads-image]][downloads-url]\n  [![Linux Build][travis-image]][travis-url]\n  [![Windows Build][appveyor-image]][appveyor-url]\n  [![Test Coverage][coveralls-image]][coveralls-url]\n\n```js\nvar express = require(\'express\')\nvar app = express()\n\napp.get(\'/\', function (req, res) {\n  res.send(\'Hello World\')\n})\n\napp.listen(3000)\n```\n\n## Installation\n\n```bash\n$ npm install express\n```\n\n## Features\n\n  * Robust routing\n  * Focus on high performance\n  * Super-high test coverage\n  * HTTP helpers (redirection, caching, etc)\n  * View system supporting 14+ template engines\n  * Content negotiation\n  * Executable for generating applications quickly\n\n## Docs & Community\n\n  * [Website and Documentation](http://expressjs.com/) - [[website repo](https://github.com/strongloop/expressjs.com)]\n  * [#express](https://webchat.freenode.net/?channels=express) on freenode IRC\n  * [Github Organization](https://github.com/expressjs) for Official Middleware & Modules\n  * Visit the [Wiki](https://github.com/strongloop/express/wiki)\n  * [Google Group](https://groups.google.com/group/express-js) for discussion\n  * [Русскоязычная документация](http://jsman.ru/express/)\n  * [한국어 문서](http://expressjs.kr) - [[website repo](https://github.com/Hanul/expressjs.kr)]\n\n**PROTIP** Be sure to read [Migrating from 3.x to 4.x](https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x) as well as [New features in 4.x](https://github.com/strongloop/express/wiki/New-features-in-4.x).\n\n## Quick Start\n\n  The quickest way to get started with express is to utilize the executable [`express(1)`](https://github.com/expressjs/generator) to generate an application as shown below:\n\n  Install the executable. The executable\'s major version will match Express\'s:\n\n```bash\n$ npm install -g express-generator@4\n```\n\n  Create the app:\n\n```bash\n$ express /tmp/foo && cd /tmp/foo\n```\n\n  Install dependencies:\n\n```bash\n$ npm install\n```\n\n  Start the server:\n\n```bash\n$ npm start\n```\n\n## Philosophy\n\n  The Express philosophy is to provide small, robust tooling for HTTP servers, making\n  it a great solution for single page applications, web sites, hybrids, or public\n  HTTP APIs.\n\n  Express does not force you to use any specific ORM or template engine. With support for over\n  14 template engines via [Consolidate.js](https://github.com/tj/consolidate.js),\n  you can quickly craft your perfect framework.\n\n## Examples\n\n  To view the examples, clone the Express repo and install the dependencies:\n\n```bash\n$ git clone git://github.com/strongloop/express.git --depth 1\n$ cd express\n$ npm install\n```\n\n  Then run whichever example you want:\n\n```bash\n$ node examples/content-negotiation\n```\n\n## Tests\n\n  To run the test suite, first install the dependencies, then run `npm test`:\n\n```bash\n$ npm install\n$ npm test\n```\n\n## People\n\nThe original author of Express is [TJ Holowaychuk](https://github.com/tj) [![TJ\'s Gratipay][gratipay-image-visionmedia]][gratipay-url-visionmedia]\n\nThe current lead maintainer is [Douglas Christopher Wilson](https://github.com/dougwilson) [![Doug\'s Gratipay][gratipay-image-dougwilson]][gratipay-url-dougwilson]\n\n[List of all contributors](https://github.com/strongloop/express/graphs/contributors)\n\n## License\n\n  [MIT](LICENSE)\n\n[npm-image]: https://img.shields.io/npm/v/express.svg\n[npm-url]: https://npmjs.org/package/express\n[downloads-image]: https://img.shields.io/npm/dm/express.svg\n[downloads-url]: https://npmjs.org/package/express\n[travis-image]: https://img.shields.io/travis/strongloop/express/master.svg?label=linux\n[travis-url]: https://travis-ci.org/strongloop/express\n[appveyor-image]: https://img.shields.io/appveyor/ci/dougwilson/express/master.svg?label=windows\n[appveyor-url]: https://ci.appveyor.com/project/dougwilson/express\n[coveralls-image]: https://img.shields.io/coveralls/strongloop/express/master.svg\n[coveralls-url]: https://coveralls.io/r/strongloop/express?branch=master\n[gratipay-image-visionmedia]: https://img.shields.io/gratipay/visionmedia.svg\n[gratipay-url-visionmedia]: https://gratipay.com/visionmedia/\n[gratipay-image-dougwilson]: https://img.shields.io/gratipay/dougwilson.svg\n[gratipay-url-dougwilson]: https://gratipay.com/dougwilson/\n',
128 silly resolved     readmeFilename: 'Readme.md',
128 silly resolved     _id: 'express@4.13.3',
128 silly resolved     dist: { shasum: '75a8ff95ed57e28568b742e360f852a719015f8c' },
128 silly resolved     _from: 'express@',
128 silly resolved     _resolved: 'https://registry.npmjs.org/express/-/express-4.13.3.tgz' } ]
129 info install express@4.13.3 into /var/www/sandbox.nodejs
130 info installOne express@4.13.3
131 info /var/www/sandbox.nodejs/node_modules/express unbuild
132 info preuninstall express@4.13.3
133 info uninstall express@4.13.3
134 verbose true,/var/www/sandbox.nodejs/node_modules,/var/www/sandbox.nodejs/node_modules unbuild express@4.13.3
135 info postuninstall express@4.13.3
136 info /var/www/sandbox.nodejs/node_modules/express unbuild
137 info preuninstall express@4.13.3
138 info uninstall express@4.13.3
139 verbose true,/var/www/sandbox.nodejs/node_modules,/var/www/sandbox.nodejs/node_modules unbuild express@4.13.3
140 info postuninstall express@4.13.3
141 error error rolling back Error: EIO, rmdir '/var/www/sandbox.nodejs/node_modules/express'
141 error error rolling back  express@4.13.3 { [Error: EIO, rmdir '/var/www/sandbox.nodejs/node_modules/express']
141 error error rolling back   errno: 55,
141 error error rolling back   code: 'EIO',
141 error error rolling back   path: '/var/www/sandbox.nodejs/node_modules/express' }
142 error Error: EIO, rmdir '/var/www/sandbox.nodejs/node_modules/express'
143 error If you need help, you may report this log at:
143 error     <http://github.com/isaacs/npm/issues>
143 error or email it to:
143 error     <npm-@googlegroups.com>
144 error System Linux 3.10.0-229.el7.x86_64
145 error command "node" "/bin/npm" "install" "express"
146 error cwd /var/www/sandbox.nodejs
147 error node -v v0.10.36
148 error npm -v 1.3.6
149 error path /var/www/sandbox.nodejs/node_modules/express
150 error code EIO
151 error errno 55
152 verbose exit [ 55, true ]

**Comment by mikestaub** [comment]
I got this same error. I ended up just npm installing the modules into a folder that is not being synced, then symlinking it to where I actually wanted to run the install. This was an acceptable workaround for me. Installing them globally also worked, but npm 3 does not install global modules into a flat dependency tree.

**Comment by kadet1090** [comment]
@mikestaub Try doing symlink of your package.json to another directory, thats not being synced and download all packeges in that place and rsync them with your tree later on. It's not best solution but it works really well and you're not making mess on your windows drive.

**Comment by GuyPaddock** [comment]
I'm guessing this has to do with the excessively deep structure that `npm` uses for dependencies of sub-packages.

**Comment by marcharding** [comment]
This should be fixed with v1.2.0. Please update and try again.

**Comment by patricknelson** [comment]
Upgraded to v1.3.0 and having exact issue. Can anyone else still reproduce this result on the newer WinNFSd? In this case CentOS7 guest on a Win7 host with Vagrant 1.8.1.

```shell
 npm ERR! Linux 3.10.0-123.el7.x86_64
 npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
 npm ERR! node v6.7.0
 npm ERR! npm  v3.10.3
 npm ERR! path /websites/myapp/node_modules/.staging
 npm ERR! code EIO
 npm ERR! errno -5
 npm ERR! syscall rmdir
 
 npm ERR! EIO: i/o error, rmdir '/websites/myapp/node_modules/.staging'
 npm ERR!
 npm ERR! If you need help, you may report this error at:
 npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by marcharding** [comment]
please see #96 for further progress on this.

i just uploaded a beta version which probably fixes this issue.

**Comment by marcharding** [comment]
Should be fixed with winnfsd 2.3.1

**Comment by mark-veenstra** [comment]
We are still encountering same issues and only workaround so far is the same @kadet1090 describes.
